// AUTO-GENERATED by scripts/generate-tools.ts — DO NOT EDIT MANUALLY
// Run `npm run generate` to regenerate from the current SDK types.
// Generated at: 2026-07-09T03:53:12.550Z

import type { ToolSchema } from "../providers/index.js";

export const GENERATED_TOOL_SCHEMAS: ToolSchema[] = [
  {
    name: "song_create_audio_track",
    description: "Inserted after the last selected track, or appended if no track is selected.",
    parameters: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "song_create_midi_track",
    description: "Inserted after the last selected track, or appended if no track is selected.",
    parameters: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "song_create_scene",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "index": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["index"],
    },
  },
  {
    name: "song_delete_track",
    description: "Deletes a track from the song. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            }
      },
      required: ["track_id"],
    },
  },
  {
    name: "song_delete_scene",
    description: "Deletes a scene from the song. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "scene_id": {
                  "type": "string",
                  "description": "Handle ID of the Scene to act on."
            }
      },
      required: ["scene_id"],
    },
  },
  {
    name: "song_duplicate_track",
    description: "Duplicates the track. The duplicate is inserted immediately after the original.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            }
      },
      required: ["track_id"],
    },
  },
  {
    name: "song_duplicate_scene",
    description: "Duplicates the scene. The duplicate is inserted immediately after the original.",
    parameters: {
      type: "object",
      properties: {
            "scene_id": {
                  "type": "string",
                  "description": "Handle ID of the Scene to act on."
            }
      },
      required: ["scene_id"],
    },
  },
  {
    name: "song_create_cue_point",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "time": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["time"],
    },
  },
  {
    name: "song_delete_cue_point",
    description: "Deletes a cue point from the song. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "cuePoint_id": {
                  "type": "string",
                  "description": "Handle ID of the CuePoint to act on."
            }
      },
      required: ["cuePoint_id"],
    },
  },
  {
    name: "song_set_tempo",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "value": {
                  "type": "number",
                  "description": "New value for tempo."
            }
      },
      required: ["value"],
    },
  },
  {
    name: "track_create_take_lane",
    description: "Appended to the end of {@link takeLanes}.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            }
      },
      required: ["track_id"],
    },
  },
  {
    name: "track_insert_device",
    description: "Inserts a built-in Live device. Drum Rack and Sampler start **empty** (no kit/sample). For immediate sound use Operator, Analog, or Drift on MIDI tracks. To load audio, import the file with resources_import_into_project then simpler_replace_sample.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "deviceName": {
                  "type": "string",
                  "description": ""
            },
            "index": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["track_id","deviceName","index"],
    },
  },
  {
    name: "track_delete_device",
    description: "Deletes a device from this track's device chain. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "device_id": {
                  "type": "string",
                  "description": "Handle ID of the Device to act on."
            }
      },
      required: ["track_id","device_id"],
    },
  },
  {
    name: "track_duplicate_device",
    description: "The duplicate is inserted directly after the original in the device chain.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "device_id": {
                  "type": "string",
                  "description": "Handle ID of the Device to act on."
            }
      },
      required: ["track_id","device_id"],
    },
  },
  {
    name: "track_delete_clip",
    description: "Deletes an arrangement clip. For session clips, use {@link ClipSlot.deleteClip}. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "clip_id": {
                  "type": "string",
                  "description": "Handle ID of the Clip to act on."
            }
      },
      required: ["track_id","clip_id"],
    },
  },
  {
    name: "track_clear_clips_in_range",
    description: "Deletes clips within the range. Clips that overlap a boundary are truncated to the range edge rather than fully deleted.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "startTime": {
                  "type": "number",
                  "description": ""
            },
            "endTime": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["track_id","startTime","endTime"],
    },
  },
  {
    name: "track_set_name",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "value": {
                  "type": "string",
                  "description": "New value for name."
            }
      },
      required: ["track_id","value"],
    },
  },
  {
    name: "track_set_mute",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for mute."
            }
      },
      required: ["track_id","value"],
    },
  },
  {
    name: "track_set_solo",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for solo."
            }
      },
      required: ["track_id","value"],
    },
  },
  {
    name: "track_set_arm",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the Track to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for arm."
            }
      },
      required: ["track_id","value"],
    },
  },
  {
    name: "midi_track_create_midi_clip",
    description: "Creates a MIDI clip on the **arrangement timeline** (linear view). For loopable clips in the session grid / main view, use clip_slot_create_midi_clip instead.",
    parameters: {
      type: "object",
      properties: {
            "midi_track_id": {
                  "type": "string",
                  "description": "Handle ID of the MidiTrack to act on."
            },
            "startTime": {
                  "type": "number",
                  "description": ""
            },
            "duration": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["midi_track_id","startTime","duration"],
    },
  },
  {
    name: "audio_track_create_audio_clip",
    description: "Creates an audio clip from a file in the track's arrangement timeline.",
    parameters: {
      type: "object",
      properties: {
            "audio_track_id": {
                  "type": "string",
                  "description": "Handle ID of the AudioTrack to act on."
            },
            "args": {
                  "type": "object",
                  "description": "Configuration object for createAudioClip.",
                  "properties": {
                        "filePath": {
                              "type": "string",
                              "description": ""
                        },
                        "startTime": {
                              "type": "number",
                              "description": ""
                        },
                        "duration": {
                              "type": "number",
                              "description": ""
                        },
                        "loopSettings": {
                              "type": "object",
                              "description": "Initial loop region and markers for a new audio clip (all positions in beats). When looping is false, loopStart equals startMarker and loopEnd equals endMarker.",
                              "properties": {
                                    "looping": {
                                          "type": "boolean",
                                          "description": "Whether the clip loops."
                                    },
                                    "startMarker": {
                                          "type": "number",
                                          "description": "Start marker position in beats."
                                    },
                                    "endMarker": {
                                          "type": "number",
                                          "description": "End marker position in beats."
                                    },
                                    "loopStart": {
                                          "type": "number",
                                          "description": "Loop start position in beats."
                                    },
                                    "loopEnd": {
                                          "type": "number",
                                          "description": "Loop end position in beats."
                                    }
                              },
                              "required": [
                                    "looping",
                                    "startMarker",
                                    "endMarker",
                                    "loopStart",
                                    "loopEnd"
                              ]
                        }
                  },
                  "required": [
                        "filePath",
                        "startTime"
                  ]
            }
      },
      required: ["audio_track_id","args"],
    },
  },
  {
    name: "clip_slot_delete_clip",
    description: "Deletes the clip in this slot. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the track containing this clip slot."
            },
            "slot_index": {
                  "type": "number",
                  "description": "0-based index of the clip slot on the track."
            }
      },
      required: ["track_id","slot_index"],
    },
  },
  {
    name: "clip_slot_create_midi_clip",
    description: "Creates a MIDI clip in the **session grid** (clip slots — the main performance view). Use slot_index 0 for the first row. Preferred when the user wants loopable session clips.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the track containing this clip slot."
            },
            "slot_index": {
                  "type": "number",
                  "description": "0-based index of the clip slot on the track."
            },
            "length": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["track_id","slot_index","length"],
    },
  },
  {
    name: "clip_slot_create_audio_clip",
    description: "Creates an audio clip in this session slot.",
    parameters: {
      type: "object",
      properties: {
            "track_id": {
                  "type": "string",
                  "description": "Handle ID of the track containing this clip slot."
            },
            "slot_index": {
                  "type": "number",
                  "description": "0-based index of the clip slot on the track."
            },
            "args": {
                  "type": "object",
                  "description": "Configuration object for createAudioClip.",
                  "properties": {
                        "filePath": {
                              "type": "string",
                              "description": ""
                        },
                        "loopSettings": {
                              "type": "object",
                              "description": "Initial loop region and markers for a new audio clip (all positions in beats). When looping is false, loopStart equals startMarker and loopEnd equals endMarker.",
                              "properties": {
                                    "looping": {
                                          "type": "boolean",
                                          "description": "Whether the clip loops."
                                    },
                                    "startMarker": {
                                          "type": "number",
                                          "description": "Start marker position in beats."
                                    },
                                    "endMarker": {
                                          "type": "number",
                                          "description": "End marker position in beats."
                                    },
                                    "loopStart": {
                                          "type": "number",
                                          "description": "Loop start position in beats."
                                    },
                                    "loopEnd": {
                                          "type": "number",
                                          "description": "Loop end position in beats."
                                    }
                              },
                              "required": [
                                    "looping",
                                    "startMarker",
                                    "endMarker",
                                    "loopStart",
                                    "loopEnd"
                              ]
                        }
                  },
                  "required": [
                        "filePath"
                  ]
            }
      },
      required: ["track_id","slot_index","args"],
    },
  },
  {
    name: "clip_set_name",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "clip_id": {
                  "type": "string",
                  "description": "Handle ID of the Clip to act on."
            },
            "value": {
                  "type": "string",
                  "description": "New value for name."
            }
      },
      required: ["clip_id","value"],
    },
  },
  {
    name: "clip_set_looping",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "clip_id": {
                  "type": "string",
                  "description": "Handle ID of the Clip to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for looping."
            }
      },
      required: ["clip_id","value"],
    },
  },
  {
    name: "clip_set_color",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "clip_id": {
                  "type": "string",
                  "description": "Handle ID of the Clip to act on."
            },
            "value": {
                  "type": "number",
                  "description": "New value for color."
            }
      },
      required: ["clip_id","value"],
    },
  },
  {
    name: "clip_set_muted",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "clip_id": {
                  "type": "string",
                  "description": "Handle ID of the Clip to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for muted."
            }
      },
      required: ["clip_id","value"],
    },
  },
  {
    name: "midi_clip_set_notes",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "midi_clip_id": {
                  "type": "string",
                  "description": "Handle ID of the MidiClip to act on."
            },
            "value": {
                  "type": "array",
                  "description": "New value for notes.",
                  "items": {
                        "type": "object",
                        "description": "A MIDI note.",
                        "properties": {
                              "pitch": {
                                    "type": "number",
                                    "description": "MIDI note number (0–127)."
                              },
                              "startTime": {
                                    "type": "number",
                                    "description": "Start time in beats."
                              },
                              "duration": {
                                    "type": "number",
                                    "description": "Duration in beats."
                              },
                              "velocity": {
                                    "type": "number",
                                    "description": "Velocity (0–127). Default: 100."
                              },
                              "releaseVelocity": {
                                    "type": "number",
                                    "description": "Release velocity (0–127). Optional."
                              },
                              "velocityDeviation": {
                                    "type": "number",
                                    "description": "Velocity deviation for randomization. Optional."
                              },
                              "muted": {
                                    "type": "boolean",
                                    "description": "Whether the note is muted."
                              },
                              "probability": {
                                    "type": "number",
                                    "description": "Note probability (0–1)."
                              },
                              "selected": {
                                    "type": "boolean",
                                    "description": "Whether the note is selected."
                              }
                        },
                        "required": [
                              "pitch",
                              "startTime",
                              "duration"
                        ]
                  }
            }
      },
      required: ["midi_clip_id","value"],
    },
  },
  {
    name: "audio_clip_set_warping",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "audio_clip_id": {
                  "type": "string",
                  "description": "Handle ID of the AudioClip to act on."
            },
            "value": {
                  "type": "boolean",
                  "description": "New value for warping."
            }
      },
      required: ["audio_clip_id","value"],
    },
  },
  {
    name: "audio_clip_set_warp_mode",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "audio_clip_id": {
                  "type": "string",
                  "description": "Handle ID of the AudioClip to act on."
            },
            "value": {
                  "type": "number",
                  "description": "One of: 0 (Beats), 1 (Tones), 2 (Texture), 3 (Repitch), 4 (Complex), 6 (ComplexPro)"
            }
      },
      required: ["audio_clip_id","value"],
    },
  },
  {
    name: "scene_set_name",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "scene_id": {
                  "type": "string",
                  "description": "Handle ID of the Scene to act on."
            },
            "value": {
                  "type": "string",
                  "description": "New value for name."
            }
      },
      required: ["scene_id","value"],
    },
  },
  {
    name: "cue_point_set_name",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "cue_point_id": {
                  "type": "string",
                  "description": "Handle ID of the CuePoint to act on."
            },
            "value": {
                  "type": "string",
                  "description": "New value for name."
            }
      },
      required: ["cue_point_id","value"],
    },
  },
  {
    name: "device_parameter_get_value",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "device_parameter_id": {
                  "type": "string",
                  "description": "Handle ID of the DeviceParameter to act on."
            }
      },
      required: ["device_parameter_id"],
    },
  },
  {
    name: "device_parameter_set_value",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "device_parameter_id": {
                  "type": "string",
                  "description": "Handle ID of the DeviceParameter to act on."
            },
            "value": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["device_parameter_id","value"],
    },
  },
  {
    name: "simpler_replace_sample",
    description: "Replaces the loaded sample with the audio file at the given absolute path.",
    parameters: {
      type: "object",
      properties: {
            "simpler_id": {
                  "type": "string",
                  "description": "Handle ID of the Simpler to act on."
            },
            "filePath": {
                  "type": "string",
                  "description": ""
            }
      },
      required: ["simpler_id","filePath"],
    },
  },
  {
    name: "rack_device_insert_chain",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "rack_device_id": {
                  "type": "string",
                  "description": "Handle ID of the RackDevice to act on."
            },
            "index": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["rack_device_id","index"],
    },
  },
  {
    name: "chain_insert_device",
    description: "Inserts a built-in Live device with its default preset into the chain. Only devices native to Live are supported — third-party plug-ins cannot be loaded this way.",
    parameters: {
      type: "object",
      properties: {
            "chain_id": {
                  "type": "string",
                  "description": "Handle ID of the Chain to act on."
            },
            "deviceName": {
                  "type": "string",
                  "description": ""
            },
            "index": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["chain_id","deviceName","index"],
    },
  },
  {
    name: "chain_delete_device",
    description: "Deletes a device from this chain. Await the returned promise to ensure the deletion has been fully processed.",
    parameters: {
      type: "object",
      properties: {
            "chain_id": {
                  "type": "string",
                  "description": "Handle ID of the Chain to act on."
            },
            "device_id": {
                  "type": "string",
                  "description": "Handle ID of the Device to act on."
            }
      },
      required: ["chain_id","device_id"],
    },
  },
  {
    name: "chain_duplicate_device",
    description: "The duplicate is inserted directly after the original in the device chain.",
    parameters: {
      type: "object",
      properties: {
            "chain_id": {
                  "type": "string",
                  "description": "Handle ID of the Chain to act on."
            },
            "device_id": {
                  "type": "string",
                  "description": "Handle ID of the Device to act on."
            }
      },
      required: ["chain_id","device_id"],
    },
  },
  {
    name: "drum_chain_set_receiving_note",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "drum_chain_id": {
                  "type": "string",
                  "description": "Handle ID of the DrumChain to act on."
            },
            "value": {
                  "type": "number",
                  "description": "New value for receivingNote."
            }
      },
      required: ["drum_chain_id","value"],
    },
  },
  {
    name: "take_lane_create_midi_clip",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "take_lane_id": {
                  "type": "string",
                  "description": "Handle ID of the take lane."
            },
            "startTime": {
                  "type": "number",
                  "description": ""
            },
            "duration": {
                  "type": "number",
                  "description": ""
            }
      },
      required: ["take_lane_id","startTime","duration"],
    },
  },
  {
    name: "take_lane_create_audio_clip",
    description: "Creates an audio clip on this take lane. See {@link AudioTrack.createAudioClip} for argument semantics.",
    parameters: {
      type: "object",
      properties: {
            "take_lane_id": {
                  "type": "string",
                  "description": "Handle ID of the take lane."
            },
            "args": {
                  "type": "object",
                  "description": "Configuration object for createAudioClip.",
                  "properties": {
                        "filePath": {
                              "type": "string",
                              "description": ""
                        },
                        "startTime": {
                              "type": "number",
                              "description": ""
                        },
                        "duration": {
                              "type": "number",
                              "description": ""
                        },
                        "loopSettings": {
                              "type": "object",
                              "description": "Initial loop region and markers for a new audio clip (all positions in beats). When looping is false, loopStart equals startMarker and loopEnd equals endMarker.",
                              "properties": {
                                    "looping": {
                                          "type": "boolean",
                                          "description": "Whether the clip loops."
                                    },
                                    "startMarker": {
                                          "type": "number",
                                          "description": "Start marker position in beats."
                                    },
                                    "endMarker": {
                                          "type": "number",
                                          "description": "End marker position in beats."
                                    },
                                    "loopStart": {
                                          "type": "number",
                                          "description": "Loop start position in beats."
                                    },
                                    "loopEnd": {
                                          "type": "number",
                                          "description": "Loop end position in beats."
                                    }
                              },
                              "required": [
                                    "looping",
                                    "startMarker",
                                    "endMarker",
                                    "loopStart",
                                    "loopEnd"
                              ]
                        }
                  },
                  "required": [
                        "filePath",
                        "startTime"
                  ]
            }
      },
      required: ["take_lane_id","args"],
    },
  },
  {
    name: "take_lane_set_name",
    description: "",
    parameters: {
      type: "object",
      properties: {
            "take_lane_id": {
                  "type": "string",
                  "description": "Handle ID of the take lane."
            },
            "value": {
                  "type": "string",
                  "description": "New value for name."
            }
      },
      required: ["take_lane_id","value"],
    },
  },
];
