import {
  AudioClip,
  AudioTrack,
  DrumChain,
  MidiClip,
  MidiTrack,
  RackDevice,
  Simpler,
  type Song,
} from '@ableton-extensions/sdk';
import * as fs from 'node:fs/promises';
import type { LiveState, DeviceInfo, ClipInfo } from '../agent/chat.js';
import { webSearch } from '../agent/web-search.js';
import { analyzeMonoCompatibility } from '../agent/phase-analysis.js';
import type { AgentContext } from './agent-context.js';
import { reg, clearRegistry } from './handle-registry.js';
import { parseHandleArg } from './generated-executor.js';
import { toJsonSafe } from '../json.js';

function findAudioTrack(song: Song<'1.0.0'>, id: string | number): AudioTrack<'1.0.0'> {
  const normalized = parseHandleArg(id);
  const track = song.tracks.find((t) => t.handle.id.toString() === normalized);
  if (!track) throw new Error(`Track "${normalized}" not found. Call get_live_state to refresh.`);
  if (!(track instanceof AudioTrack)) {
    throw new Error(`Track "${normalized}" is not an AudioTrack — mono-compatibility analysis needs audio.`);
  }
  return track;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function readDevices(devices: Song<'1.0.0'>['tracks'][0]['devices']): Promise<DeviceInfo[]> {
  return Promise.all(
    devices.map(async (d) => {
      const base: DeviceInfo = {
        id: reg(d.handle.id.toString()),
        name: d.name,
        samplePath: d instanceof Simpler ? (d.sample?.filePath ?? null) : undefined,
        parameters: await Promise.all(
          d.parameters.map(async (p) => ({
            id: reg(p.handle.id.toString()),
            name: p.name,
            value: await p.getValue(),
            min: p.min,
            max: p.max,
            defaultValue: p.defaultValue,
            isQuantized: p.isQuantized,
            valueItems: p.isQuantized
              ? p.valueItems.map((item) => ({ name: item.name, shortName: item.shortName }))
              : undefined,
          })),
        ),
        chains:
          d instanceof RackDevice
            ? await Promise.all(
                d.chains.map(async (c, ci) => ({
                  id: reg(c.handle.id.toString()),
                  name: `Chain ${ci + 1}`,
                  receivingNote: c instanceof DrumChain ? c.receivingNote : undefined,
                  devices: await readDevices(c.devices),
                })),
              )
            : undefined,
      };
      return base;
    }),
  );
}

function buildClipInfo(
  clip: Song<'1.0.0'>['tracks'][0]['clipSlots'][0]['clip'] & object,
  slotIndex: number,
): ClipInfo {
  const info: ClipInfo = {
    id: reg(clip.handle.id.toString()),
    name: clip.name,
    slotIndex,
    startTime: clip.startTime,
    endTime: clip.endTime,
    duration: clip.duration,
    startMarker: clip.startMarker,
    endMarker: clip.endMarker,
    looping: clip.looping,
    loopStart: clip.loopStart,
    loopEnd: clip.loopEnd,
    color: clip.color,
    muted: clip.muted,
    notes:
      clip instanceof MidiClip
        ? clip.notes.map((n) => ({
            pitch: n.pitch,
            startTime: n.startTime,
            duration: n.duration,
            velocity: n.velocity ?? 100,
          }))
        : undefined,
  };
  if (clip instanceof AudioClip) {
    info.filePath = clip.filePath;
    info.warping = clip.warping;
    info.warpMode = clip.warpMode;
    info.warpMarkers = clip.warpMarkers.map((m) => ({
      sampleTime: m.sampleTime,
      beatTime: m.beatTime,
    }));
  }
  return info;
}

function readClips(clipSlots: Song<'1.0.0'>['tracks'][0]['clipSlots']): ClipInfo[] {
  const result: ClipInfo[] = [];
  clipSlots.forEach((slot, idx) => {
    const clip = slot.clip;
    if (!clip) return;
    result.push(buildClipInfo(clip, idx));
  });
  return result;
}

function readArrangementClips(clips: Song<'1.0.0'>['tracks'][0]['arrangementClips']): ClipInfo[] {
  return clips.map((clip) => buildClipInfo(clip, -1));
}

async function readMixer(mixer: Song<'1.0.0'>['tracks'][0]['mixer']) {
  return {
    volume: { id: reg(mixer.volume.handle.id.toString()), value: await mixer.volume.getValue() },
    panning: { id: reg(mixer.panning.handle.id.toString()), value: await mixer.panning.getValue() },
    sends: await Promise.all(
      mixer.sends.map(async (s) => ({
        id: reg(s.handle.id.toString()),
        value: await s.getValue(),
      })),
    ),
  };
}

// ─── getLiveState ─────────────────────────────────────────────────────────────

/**
 * Builds the full session snapshot injected into the system prompt each turn.
 *
 * NOTE: Scalar/structural properties (which objects exist and what they contain)
 * are read here manually. When the SDK adds new readable properties, add them
 * to this function. Write tools (setters/methods) are auto-generated by
 * `npm run generate` — you do NOT need to touch this file for those.
 */
export async function getLiveState(song: Song<'1.0.0'>): Promise<LiveState> {
  clearRegistry();

  const readTrack = async (t: Song<'1.0.0'>['tracks'][0], type: 'midi' | 'audio' | 'return') => ({
    id: reg(t.handle.id.toString()),
    name: t.name,
    type,
    mute: t.mute,
    solo: t.solo,
    mutedViaSolo: t.mutedViaSolo,
    arm: t.arm,
    groupTrackId: t.groupTrack ? reg(t.groupTrack.handle.id.toString()) : null,
    mixer: await readMixer(t.mixer),
    devices: await readDevices(t.devices),
    sessionClips: readClips(t.clipSlots),
    arrangementClips: readArrangementClips(t.arrangementClips),
    takeLanes: t.takeLanes.map((tl) => ({
      id: reg(tl.handle.id.toString()),
      name: tl.name,
      clips: tl.clips.map((c) => ({
        id: reg(c.handle.id.toString()),
        name: c.name,
        duration: c.duration,
      })),
    })),
  });

  const [regularTracks, returnTracks] = await Promise.all([
    Promise.all(song.tracks.map((t) => readTrack(t, t instanceof MidiTrack ? 'midi' : 'audio'))),
    Promise.all(song.returnTracks.map((t) => readTrack(t, 'return'))),
  ]);

  const mainMixer = await readMixer(song.mainTrack.mixer);

  return {
    tempo: song.tempo,
    rootNote: song.rootNote,
    scaleName: song.scaleName,
    scaleMode: song.scaleMode,
    scaleIntervals: song.scaleIntervals,
    gridQuantization: song.gridQuantization,
    gridIsTriplet: song.gridIsTriplet,
    trackCount: song.tracks.length,
    tracks: [...regularTracks, ...returnTracks],
    mainTrack: {
      id: reg(song.mainTrack.handle.id.toString()),
      mixer: mainMixer,
    },
    scenes: song.scenes.map((s) => ({
      id: reg(s.handle.id.toString()),
      name: s.name,
      tempo: s.tempo,
      signatureNumerator: s.signatureNumerator,
      signatureDenominator: s.signatureDenominator,
    })),
    cuePoints: song.cuePoints.map((cp) => ({
      id: reg(cp.handle.id.toString()),
      name: cp.name,
      time: cp.time,
    })),
  };
}

/**
 * Handles custom tools that don't map 1:1 to a generated SDK call.
 * The generated executor handles everything else (see generated-executor.ts).
 */
export async function handleToolCall(
  ctx: AgentContext,
  name: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  const song = ctx.getSong();

  switch (name) {
    case 'get_live_state':
      return toJsonSafe(await getLiveState(song));

    case 'web_search': {
      const query = args['query'];
      if (typeof query !== 'string') {
        throw new Error('web_search requires a string "query" argument.');
      }
      return await webSearch(query);
    }

    case 'resources_import_into_project': {
      if (!ctx.resources) {
        throw new Error('resources_import_into_project is unavailable in this context.');
      }
      const filePath = args['file_path'];
      if (typeof filePath !== 'string' || !filePath.trim()) {
        throw new Error('resources_import_into_project requires a non-empty "file_path".');
      }
      const importedPath = await ctx.resources.importIntoProject(filePath);
      return { ok: true, importedPath };
    }

    case 'check_mono_compatibility': {
      if (!ctx.resources) {
        throw new Error('check_mono_compatibility is unavailable in this context.');
      }
      const trackIdArg = args['audio_track_id'];
      const startTime = args['start_time'];
      const endTime = args['end_time'];
      if (typeof trackIdArg !== 'string' && typeof trackIdArg !== 'number') {
        throw new Error('check_mono_compatibility requires "audio_track_id".');
      }
      if (typeof startTime !== 'number' || typeof endTime !== 'number') {
        throw new Error('check_mono_compatibility requires numeric "start_time" and "end_time".');
      }
      if (endTime <= startTime) {
        throw new Error('"end_time" must be greater than "start_time".');
      }

      const track = findAudioTrack(song, trackIdArg);
      const renderedPath = await ctx.resources.renderPreFxAudio(track, startTime, endTime);
      const renderedBuffer = await fs.readFile(renderedPath);
      const result = await analyzeMonoCompatibility(renderedBuffer);
      return { ok: true, track: track.name, startTime, endTime, ...result };
    }

    default:
      throw new Error(
        'Unknown tool: "' +
          name +
          '". Available custom tools: get_live_state, web_search, resources_import_into_project, ' +
          'check_mono_compatibility.',
      );
  }
}
