// AUTO-GENERATED by scripts/generate-tools.ts — DO NOT EDIT MANUALLY
// Run `npm run generate` to regenerate from the current SDK types.
// Generated at: 2026-07-09T03:53:12.552Z

import {
  MidiTrack, AudioTrack, MidiClip, AudioClip, ClipSlot, Device, DeviceParameter, Simpler, TakeLane, RackDevice, DrumChain,
  type Song,
} from "@ableton-extensions/sdk";
import { resolveHandle } from "./handle-registry.js";
import { toJsonSafe } from "../json.js";

// ─── Handle ID parsing ─────────────────────────────────────────────────────

/**
 * Normalizes a handle id from tool-call JSON.
 *
 * When the LLM emits a large BigInt handle as a plain JSON number, JSON.parse
 * rounds it to the nearest float64. resolveHandle() recovers the exact string
 * from the registry that getLiveState() populated before this turn.
 */
export function parseHandleArg(s: string | number): string {
  const resolved = resolveHandle(s);
  if (resolved !== null) return resolved;
  if (typeof s === "string") return s;
  return String(s);
}

// ─── Object finders ────────────────────────────────────────────────────────

function findTrack(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  const t = song.tracks.find(t => t.handle.id.toString() === normalized);
  if (!t) throw new Error(`Track "${normalized}" not found. Call song_get_tracks to refresh.`);
  return t;
}

function findScene(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  const s = song.scenes.find(s => s.handle.id.toString() === normalized);
  if (!s) throw new Error(`Scene "${normalized}" not found.`);
  return s;
}

function findClip(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  for (const track of song.tracks) {
    for (const slot of track.clipSlots) {
      if (slot.clip?.handle.id.toString() === normalized) return slot.clip;
    }
    for (const clip of track.arrangementClips) {
      if (clip.handle.id.toString() === normalized) return clip;
    }
  }
  throw new Error(`Clip "${normalized}" not found.`);
}

function allDevices(song: Song<"1.0.0">): Device<"1.0.0">[] {
  const result: Device<"1.0.0">[] = [];
  const allTracks = [...song.tracks, ...song.returnTracks, song.mainTrack];
  function collectDevices(devices: Device<"1.0.0">[]) {
    for (const d of devices) {
      result.push(d);
      if (d instanceof RackDevice) {
        for (const chain of d.chains) collectDevices(chain.devices);
      }
    }
  }
  for (const track of allTracks) collectDevices(track.devices);
  return result;
}

function findDevice(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  const device = allDevices(song).find(d => d.handle.id.toString() === normalized);
  if (!device) throw new Error(`Device "${normalized}" not found.`);
  return device;
}

function findDeviceParameter(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  for (const device of allDevices(song)) {
    for (const param of device.parameters) {
      if (param.handle.id.toString() === normalized) return param;
    }
  }
  throw new Error(`DeviceParameter "${normalized}" not found.`);
}

function findChain(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  for (const device of allDevices(song)) {
    if (device instanceof RackDevice) {
      const chain = device.chains.find(c => c.handle.id.toString() === normalized);
      if (chain) return chain;
    }
  }
  throw new Error(`Chain "${normalized}" not found.`);
}

function findRackDevice(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  const device = findDevice(song, normalized);
  if (!(device instanceof RackDevice)) throw new Error(`Device "${normalized}" is not a RackDevice.`);
  return device;
}

function findCuePoint(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  const cp = song.cuePoints.find(cp => cp.handle.id.toString() === normalized);
  if (!cp) throw new Error(`CuePoint "${normalized}" not found.`);
  return cp;
}

function findTakeLane(song: Song<"1.0.0">, id: string | number) {
  const normalized = parseHandleArg(id);
  for (const track of song.tracks) {
    for (const lane of track.takeLanes) {
      if (lane.handle.id.toString() === normalized) return lane;
    }
  }
  throw new Error(`TakeLane "${normalized}" not found.`);
}

function serializeResult(result: unknown): unknown {
  return toJsonSafe(result);
}

function findByHandleClass(song: Song<"1.0.0">, cls: string, id: string | number): unknown {
  switch (cls) {
    case "Track": case "MidiTrack": case "AudioTrack": return findTrack(song, id);
    case "Scene": return findScene(song, id);
    case "Clip": case "MidiClip": case "AudioClip": return findClip(song, id);
    case "Device": return findDevice(song, id);
    case "DeviceParameter": return findDeviceParameter(song, id);
    case "TakeLane": return findTakeLane(song, id);
    case "RackDevice": case "DrumRack": return findRackDevice(song, id);
    case "Chain": case "DrumChain": return findChain(song, id);
    case "CuePoint": return findCuePoint(song, id);
    default: throw new Error(`Cannot find object of class "${cls}" by ID`);
  }
}

// ─── Dispatcher ────────────────────────────────────────────────────────────

export async function executeGeneratedTool(
  song: Song<"1.0.0">,
  name: string,
  args: Record<string, unknown>
): Promise<unknown> {
  switch (name) {
    case "song_create_audio_track": {
      const _result = await song.createAudioTrack();
      return serializeResult(_result);
    }
    case "song_create_midi_track": {
      const _result = await song.createMidiTrack();
      return serializeResult(_result);
    }
    case "song_create_scene": {
      const _result = await song.createScene(args["index"] as number);
      return serializeResult(_result);
    }
    case "song_delete_track": {
      await song.deleteTrack(findByHandleClass(song, "Track", args["track_id"] as string | number) as never);
      return { ok: true };
    }
    case "song_delete_scene": {
      await song.deleteScene(findByHandleClass(song, "Scene", args["scene_id"] as string | number) as never);
      return { ok: true };
    }
    case "song_duplicate_track": {
      const _result = await song.duplicateTrack(findByHandleClass(song, "Track", args["track_id"] as string | number) as never);
      return serializeResult(_result);
    }
    case "song_duplicate_scene": {
      const _result = await song.duplicateScene(findByHandleClass(song, "Scene", args["scene_id"] as string | number) as never);
      return serializeResult(_result);
    }
    case "song_create_cue_point": {
      const _result = await song.createCuePoint(args["time"] as number);
      return serializeResult(_result);
    }
    case "song_delete_cue_point": {
      await song.deleteCuePoint(findByHandleClass(song, "CuePoint", args["cuePoint_id"] as string | number) as never);
      return { ok: true };
    }
    case "song_set_tempo": {
      song.tempo = args["value"] as never;
      return { ok: true };
    }
    case "track_create_take_lane": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      const _result = await _obj.createTakeLane();
      return serializeResult(_result);
    }
    case "track_insert_device": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      const _result = await _obj.insertDevice(args["deviceName"] as string, args["index"] as number);
      return serializeResult(_result);
    }
    case "track_delete_device": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      await _obj.deleteDevice(findByHandleClass(song, "Device", args["device_id"] as string | number) as never);
      return { ok: true };
    }
    case "track_duplicate_device": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      const _result = await _obj.duplicateDevice(findByHandleClass(song, "Device", args["device_id"] as string | number) as never);
      return serializeResult(_result);
    }
    case "track_delete_clip": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      await _obj.deleteClip(findByHandleClass(song, "Clip", args["clip_id"] as string | number) as never);
      return { ok: true };
    }
    case "track_clear_clips_in_range": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      await _obj.clearClipsInRange(args["startTime"] as number, args["endTime"] as number);
      return { ok: true };
    }
    case "track_set_name": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "track_set_mute": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      _obj.mute = args["value"] as never;
      return { ok: true };
    }
    case "track_set_solo": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      _obj.solo = args["value"] as never;
      return { ok: true };
    }
    case "track_set_arm": {
      const _obj = findTrack(song, args["track_id"] as string | number);
      _obj.arm = args["value"] as never;
      return { ok: true };
    }
    case "midi_track_create_midi_clip": {
      const _baseTrack = findTrack(song, args["midi_track_id"] as string | number);
      if (!(_baseTrack instanceof MidiTrack)) throw new Error("Track is not a MIDI track.");
      const _obj = _baseTrack;
      const _result = await _obj.createMidiClip(args["startTime"] as number, args["duration"] as number);
      return serializeResult(_result);
    }
    case "audio_track_create_audio_clip": {
      const _baseTrack = findTrack(song, args["audio_track_id"] as string | number);
      if (!(_baseTrack instanceof AudioTrack)) throw new Error("Track is not an Audio track.");
      const _obj = _baseTrack;
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "clip_slot_delete_clip": {
      const _track = findTrack(song, args["track_id"] as string | number);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      await _obj.deleteClip();
      return { ok: true };
    }
    case "clip_slot_create_midi_clip": {
      const _track = findTrack(song, args["track_id"] as string | number);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      const _result = await _obj.createMidiClip(args["length"] as number);
      return serializeResult(_result);
    }
    case "clip_slot_create_audio_clip": {
      const _track = findTrack(song, args["track_id"] as string | number);
      const _slotIdx = args["slot_index"] as number;
      const _obj = _track.clipSlots[_slotIdx];
      if (!_obj) throw new Error(`ClipSlot ${_slotIdx} not found.`);
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "clip_set_name": {
      const _obj = findClip(song, args["clip_id"] as string | number);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_looping": {
      const _obj = findClip(song, args["clip_id"] as string | number);
      _obj.looping = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_color": {
      const _obj = findClip(song, args["clip_id"] as string | number);
      _obj.color = args["value"] as never;
      return { ok: true };
    }
    case "clip_set_muted": {
      const _obj = findClip(song, args["clip_id"] as string | number);
      _obj.muted = args["value"] as never;
      return { ok: true };
    }
    case "midi_clip_set_notes": {
      const _baseClip = findClip(song, args["midi_clip_id"] as string | number);
      if (!(_baseClip instanceof MidiClip)) throw new Error("Clip is not a MIDI clip.");
      const _obj = _baseClip;
      _obj.notes = args["value"] as never;
      return { ok: true };
    }
    case "audio_clip_set_warping": {
      const _baseClip = findClip(song, args["audio_clip_id"] as string | number);
      if (!(_baseClip instanceof AudioClip)) throw new Error("Clip is not an Audio clip.");
      const _obj = _baseClip;
      _obj.warping = args["value"] as never;
      return { ok: true };
    }
    case "audio_clip_set_warp_mode": {
      const _baseClip = findClip(song, args["audio_clip_id"] as string | number);
      if (!(_baseClip instanceof AudioClip)) throw new Error("Clip is not an Audio clip.");
      const _obj = _baseClip;
      _obj.warpMode = args["value"] as never;
      return { ok: true };
    }
    case "scene_set_name": {
      const _obj = findScene(song, args["scene_id"] as string | number);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "cue_point_set_name": {
      const _obj = findCuePoint(song, args["cue_point_id"] as string | number);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    case "device_parameter_get_value": {
      const _obj = findDeviceParameter(song, args["device_parameter_id"] as string | number);
      const _result = await _obj.getValue();
      return serializeResult(_result);
    }
    case "device_parameter_set_value": {
      const _obj = findDeviceParameter(song, args["device_parameter_id"] as string | number);
      await _obj.setValue(args["value"] as number);
      return { ok: true };
    }
    case "simpler_replace_sample": {
      const _rawDevice = findDevice(song, args["simpler_id"] as string | number);
      if (!(_rawDevice instanceof Simpler)) throw new Error("Device is not a Simpler");
      const _obj = _rawDevice;
      const _result = await _obj.replaceSample(args["filePath"] as string);
      return serializeResult(_result);
    }
    case "rack_device_insert_chain": {
      const _obj = findRackDevice(song, args["rack_device_id"] as string | number);
      const _result = await _obj.insertChain(args["index"] as number);
      return serializeResult(_result);
    }
    case "chain_insert_device": {
      const _obj = findChain(song, args["chain_id"] as string | number);
      const _result = await _obj.insertDevice(args["deviceName"] as string, args["index"] as number);
      return serializeResult(_result);
    }
    case "chain_delete_device": {
      const _obj = findChain(song, args["chain_id"] as string | number);
      await _obj.deleteDevice(findByHandleClass(song, "Device", args["device_id"] as string | number) as never);
      return { ok: true };
    }
    case "chain_duplicate_device": {
      const _obj = findChain(song, args["chain_id"] as string | number);
      const _result = await _obj.duplicateDevice(findByHandleClass(song, "Device", args["device_id"] as string | number) as never);
      return serializeResult(_result);
    }
    case "drum_chain_set_receiving_note": {
      const _rawChain = findChain(song, args["drum_chain_id"] as string | number);
      if (!(_rawChain instanceof DrumChain)) throw new Error("Chain is not a DrumChain.");
      const _obj = _rawChain;
      _obj.receivingNote = args["value"] as never;
      return { ok: true };
    }
    case "take_lane_create_midi_clip": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string | number);
      const _result = await _obj.createMidiClip(args["startTime"] as number, args["duration"] as number);
      return serializeResult(_result);
    }
    case "take_lane_create_audio_clip": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string | number);
      const _result = await _obj.createAudioClip(args["args"] as never);
      return serializeResult(_result);
    }
    case "take_lane_set_name": {
      const _obj = findTakeLane(song, args["take_lane_id"] as string | number);
      _obj.name = args["value"] as never;
      return { ok: true };
    }
    default:
      throw new Error(`Unknown generated tool: ${name}`);
  }
}
